---
- name: Autoupdate - Install unattended-upgrades for Debian
  when:
    - autoupdate_enabled
    - ansible_os_family == 'Debian'
  ansible.builtin.package:
    name: unattended-upgrades
    state: present

- name: Autoupdate - Configuration for Debian (1/2)
  when:
    - autoupdate_enabled
    - ansible_os_family == 'Debian'
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    mode: "0664"
  with_items:
    - 10periodic
    - 50unattended-upgrades

- name: Autoupdate - Install dnf-automatic for RedHat
  when:
    - autoupdate_enabled
    - ansible_os_family == 'RedHat'
  ansible.builtin.package:
    name: dnf-automatic
    state: present

- name: Autoupdate - Configuration for RedHat (1/2)
  when:
    - autoupdate_enabled
    - ansible_os_family == 'RedHat'
  community.general.files.ini_file:
    path: /etc/dnf/automatic.conf
    section: commands
    option: upgrade_type
    value: "security"

- name: Autoupdate - Configuration for RedHat (2/2)
  when:
    - autoupdate_enabled
    - ansible_os_family == 'RedHat'
  ansible.builtin.systemd:
    name: dnf-automatic-install.timer
    state: started
    enabled: true
