---
- name: Packages - Update apt cache
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    update_cache: true

- name: Packages - Update dnf cache
  when: ansible_os_family == 'RedHat'
  ansible.builtin.dnf:
    update_cache: true

- name: Packages - Upgrade all packages
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Packages - Install base packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

- name: Configure autoupdate
  ansible.builtin.include_tasks:
    file: autoupdate.yml

- name: Configure ssh
  ansible.builtin.include_tasks:
    file: ssh.yml

- name: Configure bootloader
  ansible.builtin.include_tasks:
    file: bootloader.yml

- name: Configure swap
  ansible.builtin.include_tasks:
    file: swap.yml

- name: Configure docker
  when: docker_configure
  ansible.builtin.include_tasks:
    file: docker.yml

- name: Configure tailscale
  when: tailscale_configure
  ansible.builtin.include_tasks:
    file: tailscale.yml

- name: SELinux - Configuration
  when: ansible_os_family == 'RedHat'
  ansible.posix.selinux:
    policy: "{{ selinux_policy }}"
    state: "{{ selinux_state }}"
