---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * 4"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Configure python3
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Configure yamllint
        run: pip3 install yamllint

      - name: Run yamllint
        run: yamllint .
